// export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
// export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
// export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
// export const SIGNOUT = "SIGNOUT";

// export const CREATE_REQUEST = "CREATE_REQUEST";
// export const CREATE_SUCCESS = "CREATE_SUCCESS";
// export const CREATE_FAILURE = "CREATE_FAILURE";


export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE"
